version: '3.7'

services:
  db:
    image: mongo

    ports:
      - "27017:27017"

    volumes:
      - ./data/db:/var/lib/mongodb/data
  
    environment : 
    
      - MONGO_INITDB_ROOT_USERNAME=amitsingh
      - MONGO_INITDB_ROOT_PASSWORD=onorall
      - MONGO_INITDB_DATABASE=myonorall
      - MONGO_INITDB_USERNAME=amitsingh
      - MONGO_INITDB_PASSWORD=onorall


  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build: 
      context: . 
    image: shuaibansari/django_gunicorn:latest
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    image: shuaibansari/nginx:latest
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:

